

services:
  server:
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    networks:
      - mongo_network
    environment:
      - SPRING_APPLICATION_NAME=e-commerce
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/e-commerce # Refer to the service name 'mongodb'
      - SPRING_DATA_MONGODB_USERNAME=Abynah
      - SPRING_DATA_MONGODB_PASSWORD=Abynah_123
      - SPRING_DATA_MONGODB_DATABASE=e-commerce
      - SPRING_PROFILES_ACTIVE=dev
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_MAPPINGS_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=password
      - MANAGEMENT_ENDPOINT_HEALTH_ROLES=ADMIN
      - LOGGING_FILE_PATH=file.log
      - LOGGING_LEVEL_ROOT=info
      - LOGGING_PATTERN_FILE=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

volumes:
   mongo_data:

networks:
  mongo_network:


