pipeline {
    agent any


    stages {
        stage('Checkout') {
            steps {
                git branch: 'jenkins', url: 'https://github.com/Abynahisblue/product-management.git'
            }
        }



        stage('Build and Deploy with Docker Compose') {
            steps {
                script {

                    sh 'docker compose down'
                    sh 'docker compose build'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}